title: "Diego Aguilar-Ramírez"
author: "Diego Aguilar-Ramírez"
description: "University of Oxford"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "https://github.com/diegojehu/c_vitae/blob/main/CV/CV_DAR.pdf"}
  - {title: "Research Group", url: "https:"https://www.ctsu.ox.ac.uk/team/diego-aguilar-ramirez"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:diego.aguilar-ramirez@ndph.ox.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/diegojehu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
